# Generated by Django 5.2.17 on 2026-10-01 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0002_seed_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="kind",
            field=models.CharField(
                choices=[
                    ("lab_pi", "Lab PI (lab head)"),
                    ("lab", "Lab member"),
                    ("pi", "Principal investigator (other lab)"),
                    ("collaborator", "External collaborator"),
                    ("internal", "Institutional colleague"),
                    ("program_officer", "Program officer"),
                    ("admin", "Grants administrator"),
                    ("mentor", "Mentor / advisor"),
                    ("other", "Other"),
                ],
                default="lab",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "lab_pi")),
                fields=("kind",),
                name="single_lab_pi",
            ),
        ),
    ]
