# Generated by Django 5.2.17 on 2026-10-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0003_person_lab_pi_and_pi_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("nce", "No-cost extension"),
                    ("ended", "Ended"),
                    ("closing", "Close-out"),
                    ("closed", "Closed"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="historicalaward",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("nce", "No-cost extension"),
                    ("ended", "Ended"),
                    ("closing", "Close-out"),
                    ("closed", "Closed"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                max_length=12,
            ),
        ),
    ]
